In [68]:
# import pandas as pd
# import numpy as np
# import tensorflow as tf
# from sklearn.model_selection import train_test_split
# # from sklearn.preprocessing import StandardScaler
# from sklearn import preprocessing

# # Load and preprocess your dataset
# # Replace this with your data loading and preprocessing code
# data = pd.read_csv("dataset.csv")
# # data=data.drop('disease',axis=1)  # Your data
# # cols= data.columns
# labels = data['disease']
#   # Your labels
# le = preprocessing.LabelEncoder()
# le.fit(labels)
# y = le.transform(labels)
# # Split the data into training, validation, and test sets
# X_train, X_temp, y_train, y_temp = train_test_split(data, labels, test_size=0.3, random_state=42)
# X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# # Standardize the input features
# # scaler = StandardScaler()
# # X_train_scaled = scaler.fit_transform(X_train)
# # X_val_scaled = scaler.transform(X_val)
# # X_test_scaled = scaler.transform(X_test)

# # Build the neural network model
# model = tf.keras.Sequential([
#     tf.keras.layers.Input(shape=(4921,18)),  # Replace 'input_dim' with your actual input dimensions
#     tf.keras.layers.Dense(64, activation='relu'),
#     tf.keras.layers.Dense(32, activation='relu'),
#     tf.keras.layers.Dense(1, activation='sigmoid')  # Binary classification
# ])

# # Compile the model
# model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# # Train the model
# history = model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=32)

# # Evaluate the model
# test_loss, test_accuracy = model.evaluate(X_test, y_test)
# print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

# Make predictions
# predictions = model.predict(X_test)

# # Convert predictions to binary labels (0 or 1) based on a threshold
# threshold = 0.5
# binary_predictions = (predictions > threshold).astype(int)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [49]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load the dataset
data = pd.read_csv("dataset.csv")

# Extract labels and features
labels = data['disease']
features = data.drop('disease', axis=1)

In [51]:

# Label encode diseases
label_encoder = LabelEncoder()
encoded_features=features

# Iterate over columns and encode categorical values
for column in encoded_features.columns:
    if encoded_features[column].dtype == 'object':  # Check if column contains categorical data
        encoded_features[column] = label_encoder.fit_transform(encoded_features[column])

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,33,35,35,11,38,32,26,21,22,21,18,11,8,4,3,3,1
1,24,27,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
2,33,27,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
3,33,35,18,50,38,32,26,21,22,21,18,11,8,4,3,3,1
4,33,35,35,50,38,32,26,21,22,21,18,11,8,4,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4915,28,17,33,38,22,29,26,21,22,21,18,11,8,4,3,3,1
4916,24,31,3,35,38,32,26,21,22,21,18,11,8,4,3,3,1
4917,4,4,22,7,38,32,26,21,22,21,18,11,8,4,3,3,1
4918,24,20,42,36,27,15,26,21,22,21,18,11,8,4,3,3,1
4919,24,18,4,33,35,32,26,21,22,21,18,11,8,4,3,3,1

In [64]:

# Convert labels to numerical values using label encoding
encoded_labels = label_encoder.fit_transform(labels)

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(encoded_features, encoded_labels, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Build the neural network model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),  # Input shape should match the number of features
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')  # Binary classification
])

In [65]:

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [66]:

# Train the model
history = model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, batch_size=32)

Epoch 1/10
108/108 [==============================] - 3s 9ms/step - loss: -3381.2351 - accuracy: 0.0235 - val_loss: -11263.1982 - val_accuracy: 0.0271
Epoch 2/10
108/108 [==============================] - 1s 5ms/step - loss: -43217.8320 - accuracy: 0.0235 - val_loss: -95036.0859 - val_accuracy: 0.0271
Epoch 3/10
108/108 [==============================] - 0s 4ms/step - loss: -210898.2656 - accuracy: 0.0235 - val_loss: -357673.2812 - val_accuracy: 0.0271
Epoch 4/10
108/108 [==============================] - 0s 4ms/step - loss: -619362.3125 - accuracy: 0.0235 - val_loss: -919585.5625 - val_accuracy: 0.0271
Epoch 5/10
108/108 [==============================] - 0s 4ms/step - loss: -1408537.2500 - accuracy: 0.0235 - val_loss: -1915544.2500 - val_accuracy: 0.0271
Epoch 6/10
108/108 [==============================] - 1s 5ms/step - loss: -2679732.5000 - accuracy: 0.0235 - val_loss: -3409038.5000 - val_accuracy: 0.0271
Epoch 7/10
108/108 [==============================] - 1s 5ms/step - loss: -4513011.0000 - accuracy: 0.0235 - val_loss: -5498858.0000 - val_accuracy: 0.0271
Epoch 8/10
108/108 [==============================] - 0s 4ms/step - loss: -6983549.0000 - accuracy: 0.0235 - val_loss: -8226243.0000 - val_accuracy: 0.0271
Epoch 9/10
108/108 [==============================] - 0s 4ms/step - loss: -10148771.0000 - accuracy: 0.0235 - val_loss: -11671279.0000 - val_accuracy: 0.0271
Epoch 10/10
108/108 [==============================] - 0s 4ms/step - loss: -14071915.0000 - accuracy: 0.0235 - val_loss: -15895559.0000 - val_accuracy: 0.0271

In [67]:

# Evaluate the model
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

# Make predictions
predictions = model.predict(X_test)

# Convert predictions to binary labels (0 or 1) based on a threshold
threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

24/24 [==============================] - 0s 3ms/step - loss: -15932879.0000 - accuracy: 0.0257
Test Loss: -15932879.0000, Test Accuracy: 0.0257
24/24 [==============================] - 0s 2ms/step